#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias journal='cd ~/Gdrive/journals'
alias log='cd ~/Gdrive/logs'
alias dotfiles='cd ~/scripts/dotfiles'

function daily {
	cd ~/Gdrive/journals/daily  && konsole --fullscreen -e vim "$(date +%F).md" &
}

# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"
