#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias journal='cd ~/Gdrive/journals'
alias log='cd ~/Gdrive/logs'
alias dotfiles='cd ~/scripts/dotfiles'
alias log='cd ~/Gdrive/logs'
alias abupload='rclone move /run/media/ammar/Data/upload/ onedrive-ucl:Audiobooks -v'

function daily {
	cd ~/Gdrive/journals/daily  && konsole --hide-menubar --fullscreen -e vim "$(date +%F).md" &
}

function blog {
	cd ~/website/hugo && konsole --hide-menubar --fullscreen -e vim &
}

function website {
	cd ~/website/ammarshaqeel.com/htdocs && konsole --hide-menubar --fullscreen -e vim &
}

# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"

